name: C/C++ CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build
        setup-options: -Db_ndebug=true
        options: --verbose
        meson-version: 1.8.2
        ninja-version: 1.12.1
