name: C/C++ CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: meson setup builddir -Db_ndebug=true 
    - name: compile
      run: meson compile -C builddir
    - name: test
      run: meson test -C builddir --verbose
